wp:
  image: wordpress
  ports:
    - 8080:80
  links:
    - db:mysql
  volumes:
    - ./src:/var/www/html/wp-content/plugins/wp-baco
    - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: secret
